name: regeq
author: Teofil Camarasu <teofilcamarasu@gmail.com>

dependencies:
  - base
  - containers
  - pqueue
  - mtl
  - parsec

library:
  source-dirs: src

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - regeq
      - hspec

